import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "/Users/ayushmansatpathy/ai-project-management/src/app/globals.css"
import IconSideNav from "./Navigation/page";
import SideNav from "./Navigation/page";
import Navbar from "./Navigation/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
